id: A4A5AC7F4
title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected Words
  of the Buddha
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.849100
  last_modified_at: 2022-03-01 03:25:36.849103
