id: A4A5AC7F4
title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from the
  Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.855381
  last_modified_at: 2022-03-01 03:25:36.855388
