id: A4A5AC7F4
title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.857113
  last_modified_at: 2022-03-01 03:25:36.857116
