id: A4A5AC7F4
title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.846091
  last_modified_at: 2022-03-01 03:25:36.846094
