id: A4A5AC7F4
title: The Means for Accomplishment called the Blazing Wheel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.851059
  last_modified_at: 2022-03-01 03:25:36.851064
