id: A4A5AC7F4
title: Brief Dhāraṇī of Glorious Vajraṇakhī
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.833418
  last_modified_at: 2022-03-01 03:25:36.833426
