id: A4A5AC7F4
title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.859486
  last_modified_at: 2022-03-01 03:25:36.859488
