id: A4A5AC7F4
title: The Dhāraṇī of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:25:36.840125
  last_modified_at: 2022-03-01 03:25:36.840135
